title: lizhen9880's Zone
description: "Speak in such a way that others love to listen to you. Listen in such a way that others love to speak to you."
google_analytics: lizhen9880@gmail.com
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
